#title in header
title: 'å·¥ä½œå‚™å¿˜éŒ„'

#main info
#owner
owner: 'å¥½è¨˜æ€§ä¸å¦‚çˆ›ç­†é ­'
email: ''
info: ''
#description
desc: ''

#menu
menu:
  Works: ''
  About: ''
  Posts: /archives

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Taiwan
placelink: https://en.wikipedia.org/wiki/Taiwan
github: https://github.com/tzengshinfu
linkedin: https://linkedin.com/in/tzengshinfu
twitter: ''
instagram: ''
stackoverflow: ''

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /images/craftsman.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
